name: tests
on: [push]

jobs:
  linux-docker:
    strategy:
      fail-fast: false
      matrix:
        os: [centos7, ubuntu_22.04]
    runs-on: [ubuntu-24.04]
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
      - run: |
          cp Dockerfile.${{ matrix.os }} Dockerfile
          docker build --tag sta-${{ matrix.os }} .
      - run: |
          docker run --entrypoint /bin/bash --tty --rm sta-${{ matrix.os }} -c "cd /OpenSTA/test && ./regression || (cat results/diffs && exit 1)"

  macos:
    runs-on: [macos-14]
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
      - run: brew bundle
      - run: brew link --force --overwrite tcl-tk@8
      - run: |
          which tclsh
          ls -alh /opt/homebrew/opt/
          exit 1
          eval "$(/opt/homebrew/bin/brew shellenv)"
          export PATH="$(brew --prefix flex)/bin:$PATH"
          export PATH="$(brew --prefix bison)/bin:$PATH"
          export PATH="$(brew --prefix tcl-tk)/bin:$PATH"
          export TCL_LIBRARY="$(brew --prefix tcl-tk)/lib/libtcl8.6.dylib"
          export TCL_INCLUDE_PATH="$(brew --prefix tcl-tk)/include/tcl-tk"
          export TCL_HEADER="$(brew --prefix tcl-tk)/include/tcl-tk/tcl.h"
          cmake -S . -B build -D TCL_LIBRARY=$TCL_LIBRARY \
                              -D TCL_INCLUDE_PATH=$TCL_INCLUDE_PATH \
                              -D TCL_HEADER=$TCL_HEADER
          cd build
          make -j`sysctl -n hw.ncpu`
      - run: |
          cd test
          ./regression || (cat results/diffs && exit 1)
