name: tests
on: [push]

jobs:
  linux-docker:
    strategy:
      fail-fast: false
      matrix:
        os: [centos7, ubuntu_22.04]
    runs-on: [ubuntu-24.04]
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
      - run: |
          cp Dockerfile.${{ matrix.os }} Dockerfile
          docker build --tag sta-${{ matrix.os }} .
      - run: |
          docker run --entrypoint /bin/bash --tty --rm sta-${{ matrix.os }} -c "cd /OpenSTA/test && ./regression || (cat results/diffs && exit 1)"

  macos:
    runs-on: [macos-14]
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
      - run: brew bundle
      - run: |
          eval "$(/opt/homebrew/bin/brew shellenv)"
          export PATH="$(brew --prefix flex)/bin:$PATH"
          export PATH="$(brew --prefix bison)/bin:$PATH"
          export PATH="$(brew --prefix tcl-tk)/bin:$PATH"
          echo $PATH
          cmake -S . -B build
          cd build
          make
          sudo make install
      - run: |
          cd test
          ./regression || (cat results/diffs && exit 1)
